config/routes.rb
Rails.application.routes.draw do
  namespace 'api' do
    namespace 'v1' do
      resources :users, except: %i[new edit]
      patch '/update_password/:id', controller: :users, action: :update_password
    end
  end
  resources :episodes
  resources :seasons
  resources :shows
  resources :movies
  resources :lists

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/episode.rb
class Episode
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :original_id, type: Integer
  field :overview, type: String
  field :episode_number, type: Integer
  field :season_number, type: Integer

  belongs_to :season
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def episode_params
      params.require(:episode).permit(:title, :status, :original_id, :season_id, :show_id)
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_with(model: episode, local: true) do |form| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
        <% episode.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :original_id %>
    <%= form.number_field :original_id %>
  </div>

  <div class="field">
    <%= form.label :season_id %>
    <%= form.text_field :season_id %>
  </div>

  <div class="field">
    <%= form.label :show_id %>
    <%= form.text_field :show_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Original</th>
      <th>Season</th>
      <th>Show</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.title %></td>
        <td><%= episode.status %></td>
        <td><%= episode.original_id %></td>
        <td><%= episode.season_id %></td>
        <td><%= episode.show_id %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @episode.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @episode.status %>
</p>

<p>
  <strong>Original:</strong>
  <%= @episode.original_id %>
</p>

<p>
  <strong>Season:</strong>
  <%= @episode.season_id %>
</p>

<p>
  <strong>Show:</strong>
  <%= @episode.show_id %>
</p>

<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>